creation_rules:
  # Staging secrets
  - path_regex: overlays/staging/.*\.enc\.yaml$
    age: >-
      age1gg0wxkdew42q0glwhp4efy83cna825stw9l8n6merxr2znm8t4esvak57u

  # Production secrets
  - path_regex: overlays/production/.*\.enc\.yaml$
    age: >-
      age1gg0wxkdew42q0glwhp4efy83cna825stw9l8n6merxr2znm8t4esvak57u
