apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - secrets.enc.yaml

patches:
  # Override the hostname in HTTPRoute
  - target:
      kind: HTTPRoute
      name: notafilia
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: staging.notafilia.com

  # Override ALLOWED_HOSTS in ConfigMap
  - target:
      kind: ConfigMap
      name: notafilia-config
    patch: |-
      - op: replace
        path: /data/ALLOWED_HOSTS
        value: "staging.notafilia.com"

images:
  - name: ghcr.io/rafafuentes4/notafilia
    newTag: staging-latest
