apiVersion: ENC[AES256_GCM,data:jPo=,iv:DvF/aigCJ+j3pUgVfLLd/BQfIrxEXIaEn69RGNuqkxs=,tag:yi99aewCkBiXo3hpV80Jnw==,type:str]
kind: ENC[AES256_GCM,data:rASJgR98,iv:z0DNApckCtPF4Fhf7PtdO/YzN4aDqPQ0z+qdOuFi50s=,tag:/hhitwhofq8XdRmtFKoU7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yykjBjoM3I19uAFFi/OwCTc=,iv:RRieYPYqyzpqRQ27I4dgCV3vskLgt16yZW2nMYAj7HM=,tag:JKInzPdn9oPbUNuy5mzHjQ==,type:str]
type: ENC[AES256_GCM,data:1aAWi1nY,iv:C50P0xU/r30xqpa/7WOTtQ4e0TKMYLqfeRiG3Sx6H3c=,tag:0NbiQMp+OQ3ARHZ2T3IuOQ==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:II/rV4PEjFMvSAYOTh9DtBXY3ueJek1DCUtdhnWENnEbFpjys0ThJzSjrhAonEP1jUJ5RMy+XkWq3LCHUvrxMMEV2A==,iv:R8GULpLQypGCcrmK1tEaPnxfVmZhdpIcNfS9NfPf+y4=,tag:XubG72jcgnpJGQfOEsxrYw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:jwPeEO5EnwOHeDCmNEsFb7DS8WIXD5c7+dyrEOqn+yuJLk99iFttda3/zXP0MKTDT9Daz4XR9fgYM6E+f2cjGXbVZuLi0vOlzepVG/CtmfhvapkKNpkRX4LrTMLpKsRmAzkVPAXN3n7O7msVH/Mds35MI1IRHkPQ4Nh5/VwH,iv:J+S0byLvlNxvVJpjaNbAI3PA+9NF7nsp0LIVs234kXY=,tag:JK6fml40+IvRL8cwIiIdaA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:2jJhRbBzBnkhruNxntbx63Lbz7vSlFp/CYEd4QXqKF4I9ts=,iv:MQ8wAyRpzQscskJPT4VmG2qnSCQWtP9mSJuwy3r12TE=,tag:gZ8W/GCbRkQqP0UobfH20Q==,type:str]
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    SENTRY_DSN: ""
    TURNSTILE_KEY: ""
    TURNSTILE_SECRET: ""
    ANTHROPIC_API_KEY: ""
    DEFAULT_AI_MODEL: ENC[AES256_GCM,data:12mCXnfG+cl6GzmWszOdu5g=,iv:l2vApNCuSG7XTmmrAbmw6gfY+e7xyY2qvdAjxsEzTjs=,tag:DziAnJ2igwFbPqS2p5eORg==,type:str]
    OPENAI_API_KEY: ""
sops:
    age:
        - recipient: age1gg0wxkdew42q0glwhp4efy83cna825stw9l8n6merxr2znm8t4esvak57u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aHdZWTJQRW1VeC9mZmZC
            UFNYaVcvS1JPd1VsRlhMcTJEb3M5amxvZG5FCmF2M3ZQckNBRHI3NjRDUVAwdThY
            QTBBSlQ0TVhvVE1LSDkxUXR6M2h2UTgKLS0tIEJhK1N0YVZ1N1owcE4ybkFWZ3lQ
            ZkViNkpxbTIxaTlYdnRkNDBqNk9veGcK5ZlAveCNDB5iY6A+7vMG7Y+CgyoQZ5fl
            Equ7VpWHiAp6iXT2dYqLP94aKo1mGYfabQXzBx2KisQj8nMOJ72Apw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T16:12:42Z"
    mac: ENC[AES256_GCM,data:fuENdyD40NBD1j0EOy+w8zq0aLKIc+AKSFvilmUbgeW44zv4vlWSKSk+j8ytdRUqbfB60K75tV7KvKuvehemCCKp+a1pwplkEUuBmK/q22Yqd1nh/2URLTnv7NrGUDuAkFdbN5lAsaM5jnP0Urozg509nhpWyKGQY+rM9KB0i68=,iv:FytZBly+WeVjoBjF7JbTzVS49PAZYJywOg1a6nFt7ok=,tag:/OC3430daMVglbn63F8zRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
