apiVersion: v1
kind: Secret
metadata:
  name: notafilia-secrets
type: Opaque
stringData:
  SECRET_KEY: "REPLACE-BEFORE-ENCRYPTING"
  DATABASE_URL: "postgresql://notafilia:password@notafilia-pg-rw.staging:5432/notafilia"
  REDIS_URL: "redis://redis-master.staging:6379/0"
  AWS_ACCESS_KEY_ID: "REPLACE-BEFORE-ENCRYPTING"
  AWS_SECRET_ACCESS_KEY: "REPLACE-BEFORE-ENCRYPTING"
  SENTRY_DSN: ""
  TURNSTILE_KEY: "REPLACE-BEFORE-ENCRYPTING"
  TURNSTILE_SECRET: "REPLACE-BEFORE-ENCRYPTING"
  ANTHROPIC_API_KEY: "REPLACE-BEFORE-ENCRYPTING"
  DEFAULT_AI_MODEL: "claude-sonnet-4-6"
  OPENAI_API_KEY: "REPLACE-BEFORE-ENCRYPTING"
