apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "20.*"
    chart: redis
    helm:
      values: |
        architecture: standalone

        auth:
          enabled: false

        master:
          persistence:
            enabled: true
            size: 2Gi
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
