apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notafilia-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RafaFuentes4/notafilia-infra.git
    targetRevision: main
    path: overlays/production
    plugin:
      name: kustomize-sops
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
