apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-web.yaml
  - deployment-celery.yaml
  - deployment-beat.yaml
  - service-web.yaml
  - configmap.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/name: notafilia
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
